from channels.generic.websocket import WebsocketConsumer
from django.shortcuts import get_object_or_404
import json
from asgiref.sync import async_to_sync
from django.template.loader import render_to_string
from chat.models import ChatGroup,GroupMessage
#Here we have no access to the request object anymore, we can get info using the Scope dictionary

class ChatroomConsumer(WebsocketConsumer):
    def connect(self):
        self.user =self.scope["user"] #user
        self.chatroom_name=self.scope['url_route']['kwargs']['chatroom_name']
        self.chatroom=get_object_or_404(ChatGroup,group_name=self.chatroom_name)

        async_to_sync(self.channel_layer.group_add)(
            self.chatroom_name,
            self.channel_name #automatically generated byt the user (unique)
        )
        #We wrap our method in a async_to_sync makes the method async.
        self.accept()


    def disconnect(self, close_code):
        async_to_sync(self.channel_layer.group_discard)(
            self.chatroom_name, self.channel_name
        )
    

    def receive(self, text_data): #received data is in the format of json, we have to convert it to python object
        text_data_json=json.loads(text_data)
        body=text_data_json['body']
        
    #save message in db
        message=GroupMessage.objects.create(
           body= body,
           author= self.user,
           group=self.chatroom
        )
        
    # Event dict. fo an event handler (to broadcast the message to all group and save them)
        event = {
            'type':'message_handler',
            'message_id':message.id
        }

        async_to_sync(self.channel_layer.group_send)(
            self.chatroom_name, event
        )
        
    def message_handler(self,event):
        message_id=event['message_id']
        message=GroupMessage.objects.get(id=message_id)
        context= {
        'message': message,
        'user':self.user,
         }
        html=render_to_string("chat_requirements/partials/chat_message_p.html", context=context)
        self.send(text_data=html)