# Generated by Django 5.0.7 on 2024-10-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_url',
            new_name='profile_image_url',
        ),
    ]
