# Generated by Django 5.0.7 on 2024-10-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_profile_url_profile_profile_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
