# Generated by Django 5.0.7 on 2024-10-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_profile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
