# Generated by Django 5.0.7 on 2024-10-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_profile_following_remove_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
